name: Run build script

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Clone vcpkg
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        owner: 'microsoft'
        repository: 'vcpkg'
        branch: 'master'

    - run: chmod +x ./build.sh
      
    - run: ./build.sh

    - uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: dist/bin/

