name: Run build script

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  CMAKE_C_COMPILER: "/usr/bin/gcc13"
  CMAKE_CXX_COMPILER: "/usr/bin/g++13"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    - run: |
          sudo apt update
          sudo apt install gcc-13 g++-13 libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libgl1-mesa-dev libglu1-mesa-dev

    - run: chmod +x ./install_vcpkg.sh
    - run: ./install_vcpkg.sh
    - run: cmake --workflow --preset linux-vk-app
    - run: cmake --workflow --preset web-gl-app

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        body: |
          Download a zip below and run the game engine.
          Github Actions re-builds the zip when `$BRANCH_NAME` changes. 
        tag_name: $BRANCH_NAME
        files: |
          dist/linux-vk-app.zip
          dist/web-gl-app.zip

